### ISSUE TITLE
Alternative for react-easy-emoji.

### ISSUE THREAD

**Issue by wimpywarlord** [th3c0d3br34ker/hbd#5]
I reviewed your code, it's a great attempt 😍.

As a suggestion try using this website for emojis, its consistent with most systems: https://html-online.com/articles/colored-icon-characters-copy-paste/.

Best of luck.

**Comment by th3c0d3br34ker** [comment]
Thank you so much @wimpywarlord for having a look at my  project, really appreciate it.  I'll make the necessary changes. 😄

**Comment by th3c0d3br34ker** [comment]
refer in  PR
